### ISSUE TITLE
HLTV

### ISSUE THREAD

**Issue by qweqweqwe333** [cracker0dks/Twitchstreamer#1]
Hi, thanks for coding this.

I usually open streams through either hltv.org or esportlivescore.com. I noticed the only way the userscript works is if I do twitch.tv/channel. Anything else is not getting picked up.

Is it possible to modify the userscript so it picks up streams for the sites above?

**Comment by cracker0dks** [comment]
Thanks for your feedback. Maybe it would be consistent to catch all sites and played twitch streams (no vods ofc). I will take a look at this soon. stay tuned :)

**Comment by cracker0dks** [comment]
Updated the userscript c239792d0d2b5eeef8f7015e98474e6921243c46 should be working on every site now. can you confirm?

**Comment by qweqweqwe333** [comment]
Working great. Thank you.
